{{- $releaseName := .Release.Name -}}
{{- $servicePort := .Values.httpPort -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: ImplementationSpecific
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-%s" $releaseName "gitlab" | trunc 63) "servicePort" $servicePort "context" $)  | nindent 14 }}
  {{- end }}
