{{- if .Values.horizon.ingress.hosts }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: horizon-listener
spec:
  rules:
    {{- range .Values.horizon.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: ImplementationSpecific
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" "el-horizon-listener" "servicePort" 8080 "context" $)  | nindent 14 }}
    {{- end }}
{{- end }}
