{{- if .Values.enableV1betaEventListener }}
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: horizon-listener
spec:
  serviceAccountName: tekton-triggers-sa
  resources:
    kubernetesResource:
      replicas: {{ .Values.eventListener.replicas }}
      spec:
        template:
          spec:
            containers:
            - resources:
                requests:
                  memory: 32Mi
                  cpu: 1m
                limits:
                  memory: 256Mi
                  cpu: 100m
  triggers:
    - bindings:
      - ref: horizon-taskbinding
      template:
        ref: horizon-triggertemplate
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
                - key: pipelineJSONBlob
                  expression: "body.pipelineJSONBlob.marshalJSON()"
{{- end }}
