{{- if not .Values.enableV1betaEventListener }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: horizon-listener
spec:
  serviceAccountName: tekton-triggers-sa
  replicas: {{ .Values.eventListener.replicas }}
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            containers:
            - resources:
                requests:
                  memory: 32Mi
                  cpu: 1m
                limits:
                  memory: 256Mi
                  cpu: 100m
  triggers:
    - bindings:
      - ref: horizon-taskbinding
      template:
        name: horizon-triggertemplate
      interceptors:
        - cel:
            overlays:
              - key: pipelineJSONBlob
                expression: "body.pipelineJSONBlob.marshalJSON()"
{{- end }}
