name: gitlab
apiVersion: v2
version: 2.0.2
appVersion: 15.5.1
description: GitLab Community Edition
keywords:
- git
- ci
- deploy
- issue tracker
- code review
- wiki
home: https://about.gitlab.com

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
