nameOverride:

registry: "docker.io"
image: gitlab/gitlab-ce
imageTag: "15.5.1-ce.0"

ingress:
  enabled: true
  annotations:
  hosts:
    - gitlab.mac.local

persistence:
  enabled: false
  existingClaim: ""
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: ""

resources:
  requests:
    memory: 4Gi
    cpu: 2
  limits:
    memory: 4Gi
    cpu: 2

httpPort: 80

config:
  GITLAB_ROOT_EMAIL: "gitlab-admin@gitlab.example.com"
  GITLAB_ROOT_PASSWORD: "root1234"
  GITLAB_ROOT_ACCESS_TOKEN: "token-string-here123"
  GITLAB_HOST: gitlab.mac.local
  GITLAB_PORT: 80
  GITLAB_TIMEZONE: "Asia/Shanghai"
