{{- if .Values.core.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "horizon.core" . }}
  labels:
{{ include "horizon.labels" . | indent 4 }}
    component: core
spec:
  endpoints:
    - port: http
      path: {{ .Values.core.serviceMonitor.path }}
      {{- with .Values.core.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.core.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- if .Values.core.serviceMonitor.relabelings }}
      relabelings:
      {{- toYaml .Values.core.serviceMonitor.relabelings | nindent 4 }}
      {{- end }}
  selector:
    matchLabels:
{{ include "horizon.labels" . | indent 6 }}
      component: core
{{- end}}


