{{- if .Values.core.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "horizon.core" . }}
  labels:
{{ include "horizon.labels" . | indent 4 }}
    component: core
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
  selector:
    matchLabels:
{{ include "horizon.labels" . | indent 6 }}
      component: core
{{- end}}


