{{- if .Values.core.cloudEventIngress.enabled -}}
  {{- $fullName := printf "%v-%v" (include "horizon.core" .) "cloudevent" -}}
  {{- $svcPort := .Values.core.cloudEventService.port -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "horizon.labels" . | nindent 4 }}
  {{- with .Values.core.cloudEventIngress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.core.cloudEventIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ $.Values.core.cloudEventIngress.pathType}}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" $fullName "servicePort" $svcPort "context" $)  | nindent 14 }}
          {{- end }}
    {{- end }}
{{- end }}
